account/urls.py
from django.urls import path, include
from .views import category as category_views,\
    product as product_views,\
    main as main_views

app_name = 'account'

urlpatterns = [
    path('', main_views.AdminDashboard.as_view(), name='dashboard'),
    
    path('products/', include([
        path('', product_views.AllProducts.as_view(), name='products'),
        path('add/', include([
            path('', main_views.ProductQuickAccess.as_view(), name='products_quick'),
            path('cpu/', product_views.AddCpuProduct.as_view(), name='add_cpu'),
            path('gpu/', product_views.AddGpuProduct.as_view(), name='add_gpu'),
            path('ram/', product_views.AddRamProduct.as_view(), name='add_ram'),
            path('mainboard/', product_views.AddMainboardProduct.as_view(), name='add_mainboard'),
            path('power/', product_views.AddPowerProduct.as_view(), name='add_power'),
            path('fan/', product_views.AddFanProduct.as_view(), name='add_fan'),
            path('case/', product_views.AddCaseProduct.as_view(), name='add_case'),
            path('disk/', product_views.AddDiskProduct.as_view(), name='add_disk'),
            path('battery/', product_views.AddBatteryProduct.as_view(), name='add_battery'),
            path('monitor/', product_views.AddMonitorProduct.as_view(), name='add_monitor'),
            path('webcam/', product_views.AddWebcamProduct.as_view(), name='add_webcam'),
            path('keyboard/', product_views.AddKeyboardProduct.as_view(), name='add_keyboard'),
            path('mouse/', product_views.AddMouseProduct.as_view(), name='add_mouse'),
            path('pad/', product_views.AddPadProduct.as_view(), name='add_pad'),
            path('cable/', product_views.AddCableProduct.as_view(), name='add_cable'),
            path('laptop/', product_views.AddLaptopProduct.as_view(), name='add_laptop'),
            path('assembled-case/', product_views.AddAssembledcase.as_view(), name='add_sc'),
            path('mouse-keyboard-boundle/', product_views.AddBoundleMK.as_view(), name='add_boundle'),
            ])
        ),
        path('<slug:slug>/', include([
            path('update/', product_views.UpdateProduct.as_view(), name='delete_product'),
            path('delete/', product_views.DeleteProduct.as_view(), name='update_product'),
            ])
        ),
        ])
    ),
    
    path('categories/', include([
        path('', category_views.ListCategory.as_view(), name='category_list'),
        path('add/', category_views.AddCategory.as_view(), name='add_category'),
        path('<slug:slug>/', include([
            path('update/', category_views.UpdateCategory.as_view(), name='update_category'),
            path('remove/', category_views.RemoveCategory.as_view(), name='remove_category'),
            ])
        ),
        ])
    ),
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('web.urls')),
    path('django-admin/', admin.site.urls),
    path('admin-panel/', include('account.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
]

web/models.py
import os
from django.db import models
from django.urls import reverse_lazy
from .validators import NoramlFieldValidator, AdvancedFieldValidator
from django.utils import timezone
from . import information
from django.forms import ValidationError
# Create your models here.

class Product(models.Model):
    STATUS_CHOICES = (
        ('p', 'منتشر شده'),
        ('d', 'پیش نویس')
    )
    
    name = models.CharField(verbose_name='نام', max_length=512)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, related_name='category', verbose_name='دسته بندی', null=True)
    price = models.PositiveIntegerField(verbose_name='قیمت')
    cpu = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='پردازنده',
        validators=[AdvancedFieldValidator(information.CPU_INF, information.CPU_NULLABLE_FIELDS).validator]
    )
    gpu = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='کارت گرافیک',
        validators=[AdvancedFieldValidator(information.GPU_INF, information.GPU_NULLABLE_FIELDS).validator]
    )
    ram = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='رم',
        validators=[AdvancedFieldValidator(information.RAM_INF, information.RAM_NULLABLE_FIELDS).validator]
    )
    main_board = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='مادربورد',
        validators=[NoramlFieldValidator(information.MAIN_BOARD_INF).validator]
    )
    power = models.JSONField(
        null=True,
        blank=True,
        verbose_name='پاور',
        validators=[NoramlFieldValidator(information.POWER_INF).validator]
    )
    fan = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='خنک کننده',
        validators=[NoramlFieldValidator(information.FAN_INF).validator]
    )
    case = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='پوسته کیس',
        validators=[NoramlFieldValidator(information.CASE_INF).validator]
    )
    disk = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='دیسک',
        validators=[AdvancedFieldValidator(information.DISK_INF, information.DISK_NULLABLE_FIELDS).validator]
    )
    battery = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='باطری',
        validators=[AdvancedFieldValidator(information.BATTERY_INF, information.BATTERY_NULLABLE_FIELDS).validator]
    )
    monitor = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='مانیتور',
        validators=[AdvancedFieldValidator(information.MONITOR_INF, information.MONITOR_NULLABLE_FIELDS).validator]
    )
    webcam = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='وبکم',
        validators=[NoramlFieldValidator(information.WEBCAM_INF).validator]
    )
    mouse = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='ماوس',
        validators=[NoramlFieldValidator(information.MOUSE_INF).validator]
    )
    keyboard = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='کیبورد',
        validators=[AdvancedFieldValidator(information.KEYBOARD_INF, information.KEYBOARD_NULLABLE_FIELDS).validator]
    )
    pad = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='پدماوس',
        validators=[NoramlFieldValidator(information.PAD_INF).validator]
    )
    cable = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='کابل',
        validators=[NoramlFieldValidator(information.CABLE_INF).validator]
    )
    sticker = models.JSONField(
        null=True, 
        blank=True, 
        verbose_name='برچسب'
        )
    weight = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='وزن'
    )
    # comments = models.ManyToManyField('Comment',null=True, blank=True, verbose_name='نظرات')
    colors = models.JSONField('رنگ های موجود', max_length=50)
    flags = models.JSONField()
    slug = models.SlugField(verbose_name='اسلاگ', unique=True)
    explain = models.TextField(verbose_name='توضیحات بیشتر')
    quantity = models.IntegerField(verbose_name='موجودی')
    created = models.DateTimeField(verbose_name='زمان ساخت', auto_now_add=True)
    off_price = models.PositiveIntegerField(verbose_name='مبلغ تخفیف', help_text='مبلغ تخفیفی که میخواهید بر روی کالا اعمال شود.', null=True, blank=True)
    status = models.CharField(default='d', verbose_name='وضعیت', choices=STATUS_CHOICES, max_length=20)
    publish = models.DateTimeField(verbose_name='زمان انتشار', null=True, blank=True)
    
    @property
    def display_price(self,):
        return f'{self.price:,}'
    
    class Meta:
        ordering = ('-publish',)
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'
    
    def save(self, *args, **kwargs):
        if self.status == 'p':
            self.publish = timezone.now()
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse_lazy('account:products')

    
class Category(models.Model):
    name = models.CharField(max_length=256, verbose_name='نام')
    position = models.IntegerField(verbose_name='مکان قرارگیری')
    slug = models.SlugField(unique=True, verbose_name='اسلاگ')
    image = models.ImageField(verbose_name='پیش نمایش دسته بندی', upload_to='media/categories/')
    
    class Meta:
        ordering = ('position',)
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        
    def __str__(self):
        return self.name

    def save(self, *args,**kwargs):
        try:
            _object = Category.objects.get(id=self.pk)
            if _object.image and (_object.image != self.image):
                os.remove(_object.image.path)
        except Category.DoesNotExist :
            pass
        return super().save(*args, **kwargs)

    

class ProductItem(models.Model):
    item = models.ForeignKey(Product(), on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()
    colors = models.JSONField()    

    def clean(self):
        for i in self.colors:
            if i not in self.item.colors.keys():
                raise ValidationError('color id not in exist on colors product!')
        super().clean()

    def __str__(self):
        return self.item.name

templates/admin-panel/add-item-product.html
{% extends './index.html' %}
{% load widget_tweaks %}

{% block main %}
<div class='content'>
    <div class='container-fluid'> 
        <div class='row'>
            <div class='col-md-12'>
                <div class='card'>    
                    <div class='card-header' data-background-color="purple">
                        
                        {% block title %}
                            اضافه کردن
                        {% endblock  %}
                            {{item_label}}
                    </div>
                    <div class='card-content'>
                        <form method='POST' enctype="multipart/form-data">
                            <div class='row'>
                                {% csrf_token %}                                
                                {% for i in form %}
                                <div class='col-md-6'>
                                    <div class="form-group label-floating is-empty">
                                        {{i|add_class:'form-control'}}
                                        {{i.errors}}
                                        <label class="control-label">{{i.label}}</label>
                                        <span class="material-input"></span>
                                        <i class='text-muted'>{{i.help_text}}</i>
                                    </div>
                                </div>
                                {% endfor %}
                                
                                <div class='col-md-12'>
                                    <button type="submit" class="btn btn-primary pull-right">
                                    {% block title_button %}
                                        افزودن
                                    {% endblock  %}
                                        <div class="ripple-container"></div>
                                    </button>
                                    
                                    {% block delete_btn %}
                                        
                                    {% endblock  %}
                                        
                                </div>
                        </form>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>


{% endblock main %}
    


{% block staticjs %}
		<script>
            let all_selects = document.getElementsByTagName('select');
            for (index = 0; index < all_selects.length; ++index) {
                all_selects[index].parentNode.classList.remove('is-empty');
                all_selects[index].parentNode.classList.add('is-focused');
            }
            

            let all_options = document.getElementsByTagName('option');
            for (index = 0; index < all_options.length; ++index) {
                if (all_options[index].selected == true){
                    all_options[index].parentNode.parentNode.classList.remove("is-empty");
                }
            }

            let all_input = document.getElementsByTagName('input');
            for (index = 0; index < all_input.length; ++index) {
                if (all_input[index].value){
                    all_input[index].parentNode.classList.remove("is-empty");
                }
                
                let input_have_error = all_input[index].parentNode;
                for (u = 0; u < input_have_error.children.length; u++){
                    if (input_have_error.children[u].nodeName == 'UL'){
                        input_have_error.classList.add('has-error');
                    }
                }

            }

            let input_files = $('input[type=file]').parent().children('label');
            for (i=0; i < input_files.length; i++){
            input_files[i].style.left = 0;
            }
            
            $(document).ready(function() {
                $(document).on('click','.errorlist', function() {
                    $(this).remove();
                });
            });

        </script>
        {% endblock %}

templates/admin-panel/list-products.html
{% extends './index.html' %}
{% block main %}        
    <div class="content">
        {% if messages %}
            <ul class='messages'>
                {% for i in messages %}
                    <div class='bg-{{i.tags}} message'>
                        <p class='text-white'>{{i}}</p>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header" data-background-color="purple">
                            <h4 class="title">لیست محصولات</h4>
                            <p class="category">لیست محصولات اضافه شده توسط ادمین ها</p>
                        </div>
                        <div class="card-content table-responsive">
                            <table class="table">
                                <thead class="text-primary">
                                    <tr>
                                        <th>نام</th>
                                        <th>دسته بندی</th>
                                        <th>قیمت</th>
                                        <th>موجودی</th>
                                        <th>زمان افزودن</th>
                                        <th>وضعیت انتشار</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in data %}
                                    <tr>
                                        <td><a href='{% url "account:update_product" i.slug %}'>{{i.name}}</a></td>
                                        <td>{{i.category.name}}</td>
                                        <td class="text-primary">{{i.display_price}}تومان</td>
                                        <td>{{i.quantity}}</td>
                                        <td>{{i.created}}</td>
                                        <td>{{i.get_status_display}}</td>
                                    </tr>

                                    {% empty %}
                                    <td class='text-danger'>محصولی وجود ندارد</td>
                                    {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main %}

templates/admin-panel/quick-add-product.html
{% extends './index.html' %}


{% block main %}

    <div class='content'>
        <div class='container-fluid'> 
            <div class='row'>
                <div class='col-md-12'>
                    <div class='card'>    
                        <div class='card-header' data-background-color="purple">
                            افزودن محصول
                        </div>
                        <div class='card-content'>
                            <div class='row' id='quick-tab-products'>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_cpu' %}">
                                    {% comment %} <a href="{% url 'account:add_cpu' %}"> {% endcomment %}
                                        افزودن پردازنده
                                    {% comment %} </a> {% endcomment %}
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_gpu' %}">
                                    افزودن کارت گرافیک
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_ram' %}">
                                    افزودن حافظه رم
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_mainboard' %}">
                                    افزودن مادربورد
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_power' %}">
                                    افزودن منبع تغذیه
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_fan' %}">
                                    افزودن خنک کننده
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_case' %}">
                                    افزودن قاب کیس
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_disk' %}">
                                    افزودن دیسک
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_battery' %}">
                                    افزودن باطری
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_monitor' %}">
                                    افزودن صفحه نمایش
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_webcam' %}">
                                    افزودن وبکم
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_keyboard' %}">
                                    افزودن کیبورد
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_mouse' %}">
                                    افزودن ماوس
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_pad' %}">
                                    افزودن پدماوس
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_cable' %}">
                                    افزودن کابل
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_laptop' %}">
                                    افزودن لپ تاپ
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_sc' %}">
                                    افزودن کیس اسمبل شده
                                </a>
                                <a class='col-md-3 p-3 m-3' data-background-color='purple' href="{% url 'account:add_boundle' %}">
                                    افزودن باندل ماوس و کیبورد
                                </a>
                            </div>
                        </div>
                    </div>    
                </div>
            </div>
        </div>
    </div>
    
{% endblock main %}
    

templates/admin-panel/rightside-bar.html
{% load static %}
{% load utils %}
<div class="sidebar" data-color="purple" data-image="{% static 'admin-panel/assets/img/sidebar-1.jpg' %}">
    <div class="logo">
        <a href="http://www.sevdaweb.ir" class="simple-text">
            پنل آنلاین شاپ
        </a>
    </div>

    <div class="sidebar-wrapper">
        <ul class="nav">
            <li {% if request.resolver_match.url_name == 'dashboard' %}class='active'{% endif %}>
                <a href="{% url 'account:dashboard' %}">
                    <i class="material-icons">dashboard</i>
                    <p>پیشخوان</p>
                </a>
            </li>
            <hr>
            
                
            <li {% if request.resolver_match.route|check_start_url %}class='active'{% endif %}>
                <a href="{% url 'account:products_quick' %}">
                    <i class="material-icons">person</i>
                    <p>افزودن محصول</p>
                </a>
            </li>
            <li {% if request.resolver_match.url_name == 'products' %}class='active'{% endif %}>
                <a href="{% url 'account:products' %}">
                    <i class="material-icons">library_books</i>
                    <p>لیست محصولات</p>
                </a>
            </li>
            <hr>
            <li {% if request.resolver_match.url_name == 'add_category' %}class='active'{% endif %} >
                <a href="{% url 'account:add_category' %}">
                    <i class="material-icons">content_paste</i>
                    <p>اضافه کردن دسته بندی</p>
                </a>
            </li>
            <li {% if request.resolver_match.url_name == 'category_list' %}class='active'{% endif %} >
                <a href="{% url 'account:category_list' %}">
                    <i class="material-icons">content_paste</i>
                    <p>لیست دسته بندی</p>
                </a>
            </li>
            <hr>
            <li>
                <a href="icons.html">
                    <i class="material-icons">bubble_chart</i>
                    <p>سفارش های دریافتی</p>
                </a>
            </li>
            <li>
                <a href="maps.html">
                    <i class="material-icons">person</i>
                    <p>کاربرها</p>
                </a>
            </li>
            {% comment %} <li>
                <a href="notifications.html">
                    <i class="material-icons text-gray"></i>
                    <p></p>
                </a>
            </li> {% endcomment %}
        </ul>
    </div>
</div>

templates/admin-panel/update-product.html
{% extends './add-item-product.html' %}

{% block title %}
به روزرسانی
{% endblock %}

{% block title_button %}
به روز کردن
{% endblock %}