account/urls.py
from django.urls import path, include
from .views import category as category_views,\
    product as product_views,\
    main as main_views

app_name = 'account'

urlpatterns = [
    path('', main_views.AdminDashboard.as_view(), name='dashboard'),
    
    path('products/', include([
        path('', product_views.AllProducts.as_view(), name='products'),
        path('add/', include([
            path('', main_views.ProductQuickAccess.as_view(), name='products_quick'),
            path('cpu/', product_views.AddCpuProduct.as_view(), name='add_cpu'),
            path('gpu/', product_views.AddGpuProduct.as_view(), name='add_gpu'),
            path('ram/', product_views.AddRamProduct.as_view(), name='add_ram'),
            path('mainboard/', product_views.AddMainboardProduct.as_view(), name='add_mainboard'),
            path('power/', product_views.AddPowerProduct.as_view(), name='add_power'),
            path('fan/', product_views.AddFanProduct.as_view(), name='add_fan'),
            path('case/', product_views.AddCaseProduct.as_view(), name='add_case'),
            path('disk/', product_views.AddDiskProduct.as_view(), name='add_disk'),
            path('battery/', product_views.AddBatteryProduct.as_view(), name='add_battery'),
            path('monitor/', product_views.AddMonitorProduct.as_view(), name='add_monitor'),
            path('webcam/', product_views.AddWebcamProduct.as_view(), name='add_webcam'),
            path('keyboard/', product_views.AddKeyboardProduct.as_view(), name='add_keyboard'),
            path('mouse/', product_views.AddMouseProduct.as_view(), name='add_mouse'),
            path('pad/', product_views.AddPadProduct.as_view(), name='add_pad'),
            path('cable/', product_views.AddCableProduct.as_view(), name='add_cable'),
            path('laptop/', product_views.AddLaptopProduct.as_view(), name='add_laptop'),
            path('assembled-case/', product_views.AddAssembledcase.as_view(), name='add_sc'),
            path('mouse-keyboard-boundle/', product_views.AddBoundleMK.as_view(), name='add_boundle'),
            ])
        ),
        path('<slug:slug>/', include([
            path('update/', product_views.UpdateProduct.as_view(), name='delete_product'),
            path('delete/', product_views.DeleteProduct.as_view(), name='update_product'),
            ])
        ),
        ])
    ),
    
    path('categories/', include([
        path('', category_views.ListCategory.as_view(), name='category_list'),
        path('add/', category_views.AddCategory.as_view(), name='add_category'),
        path('<slug:slug>/', include([
            path('update/', category_views.UpdateCategory.as_view(), name='update_category'),
            path('remove/', category_views.RemoveCategory.as_view(), name='remove_category'),
            ])
        ),
        ])
    ),
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('web.urls')),
    path('django-admin/', admin.site.urls),
    path('admin-panel/', include('account.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
]

account/views/category.py
from ..mixins import AdminsMixin, AdminPanelTemplateBase, SuccessProccessMixin, AddModelNameTemplateMixin
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy
from web.models import Category
from .. import forms

class ListCategory(AdminsMixin, AdminPanelTemplateBase, generic.ListView):
    model = Category
    template_name = 'category/list-category.html'
    paginate_by = 15
    context_object_name = 'data'


class AddCategory(AdminsMixin, AdminPanelTemplateBase,
                SuccessProccessMixin, AddModelNameTemplateMixin,
                generic.CreateView):
    model = Category
    form_class = forms.CategoryForm
    template_name = 'add-item-product.html'
    success_message = 'افزوده شد'
    def get_success_url(self):
        return reverse_lazy('account:category_list')


class UpdateCategory(AdminsMixin, AdminPanelTemplateBase,
                    SuccessProccessMixin, AddModelNameTemplateMixin, 
                    generic.UpdateView):
    model = Category
    form_class = forms.CategoryForm
    template_name = 'category/update-category.html'
    success_message = 'به روزرسانی شد'

    def get_success_url(self):
        return reverse_lazy('account:category_list')
    
    def get_object(self):
        slug = self.kwargs.get(self.slug_url_kwarg)
        return get_object_or_404(Category, slug=slug)



class RemoveCategory(AdminsMixin, AdminPanelTemplateBase,
                     AddModelNameTemplateMixin, generic.DeleteView):
    model = Category
    template_name = 'category/delete-category.html'

    def get_object(self):
        slug = self.kwargs.get(self.slug_url_kwarg)
        return get_object_or_404(Category, slug=slug)
    
    def get_success_url(self):
        return reverse_lazy('account:category_list')
    
    def delete(self, request, *args, **kwargs):
        messages.success(request, f'دسته بندی {self.get_object().name} با موفقیت  حذف شد!')
        return super().delete(request, *args, **kwargs)

templates/admin-panel/category/delete-category.html
{% extends '../index.html' %}

{% block main %}
<div class='content'>
    <div class='container-fluid'> 
        <div class='row'>
            <div class='col-md-12'>
                <div class='card'>    
                    <div class='card-header' data-background-color="red">
                        حذف {{item_label}} {{object.name}}
                    </div>
                    <div class='card-content'>
                        <form method='POST'>
                            <div class='row'>
                                {% csrf_token %} 
                                <div class='col-md-12 text-center'>
                                    <div class="text-danger">
                                        <p>آیا از حذف {{item_label}} {{object.name}} مطمئن هستید؟
                                    </div>
                                    <div class='text-center row'>
                                        <button type="submit" class="btn btn-danger pull-center">
                                            حذف
                                        </button>
                                        <a href="{% url 'account:update_category' request.resolver_match.kwargs.slug %}" class="btn btn-success pull-center">
                                            بازگشت
                                            <div class="ripple-container"></div>
                                        </a>
                                    </div>
                                </div>
                            </div>                               
                        </form>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>


{% endblock main %}

templates/admin-panel/category/list-category.html
{% extends '../index.html' %}
{% block main %}
        
    <div class="content">
        
        {% if messages %}
            <ul class='messages'>
                {% for i in messages %}
                    <div class='bg-{{i.tags}} message'>
                        <p class='text-white'>{{i}}</p>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header" data-background-color="purple">
                            <h4 class="title">لیست دسته بندی ها</h4>
                        </div>
                        <div class="card-content table-responsive">
                            <table class="table">
                                <thead class="text-primary">
                                    <tr>
                                        <th>نام</th>
                                        <th>اسلاگ</th>
                                        <th>مکان قرارگیری</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in data %}
                                    <tr>
                                        {% comment %} <td><a href='{% url "account:update_category" i.slug %}'>{{i.name}}</a></td> {% endcomment %}
                                        <td><a href='{% url "account:update_category" i.slug %}'>{{i.name}}</a></td>
                                        <td>{{i.slug}}</td>
                                        <td>{{i.position}}</td>
                                    </tr>

                                    {% empty %}
                                    <td class='text-danger'>محصولی وجود ندارد</td>
                                    {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main %}

templates/admin-panel/category/update-category.html
{% extends "../add-item-product.html" %}


{% block title_button %}
    ویرایش
{% endblock title_button %}
    

{% block delete_btn %}
    <a href="{% url 'account:remove_category' request.resolver_match.kwargs.slug %}" class='btn btn-danger'>حذف</a>
{% endblock  %}
    